title: Sebastian Piaścik - Freelancer - Front-end Developer | Tworzenie stron internetowych
author:
  name: Sebastian Piaścik
  email: 'sebastian.piascik97@gmail.com'
metadata:
    description: 'Sebastian Piaścik - Freelancer - Front-end developer. Specjalizuje się w tworzeniu responsywnych stron internetowych, szablonów allegro oraz prostych sklepów e-commerce. Sprawdź moje portfolio.'
